Repetido/Controllers/AperturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repetido.Models.Modelos;
using System.Xml.Linq;
using System.Xml;
using Repetido.Controllers;
using System.Diagnostics;
namespace Repetido.Controllers
{
    public class AperturaController : Controller
    {
        public static Stopwatch osW = new Stopwatch();
        public static List<PersonalizadaModel> ListaColores = new List<PersonalizadaModel>();
        public static List<string> colores = new List<string>();
        public static List<string> colores2 = new List<string>();
        public static int color1 = 0, color2 = 0;

        public ActionResult Xtreme()
        {
            return View();
        }
        public ActionResult Personalizada()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Personalizada(string Negro, string Blanco, string Rojo, string Cafe, string Anaranjado,
            string Magenta, string Verde, string Celeste, string Amarillo, string Azul)
        {
            if (Negro == null && Blanco == null && Rojo == null && Cafe == null && Anaranjado == null && Magenta == null
                && Verde == null && Celeste == null && Amarillo == null && Azul == null)
            {
                return RedirectToAction("Jugar", "Pantallaprincipal");
            }
            else
            {
                if (Negro != null)
                {
                    colores.Add("black");
                }
                if (Blanco != null)
                {
                    colores.Add("white");
                }
                if (Rojo != null)
                {
                    colores.Add("red");
                }
                if (Cafe != null)
                {
                    colores.Add("coffe");
                }
                if (Anaranjado != null)
                {
                    colores.Add("orange");
                }


                if (Magenta != null)
                {
                    colores2.Add("magenta");
                }
                if (Verde != null)
                {
                    colores2.Add("greenF");
                }
                if (Celeste != null)
                {
                    colores2.Add("skyblue");
                }
                if (Amarillo != null)
                {
                    colores2.Add("yellow");
                }
                if (Azul != null)
                {
                    colores2.Add("blue");
                }
            }

            for (int i = 0; i < 64; i++)
            {
                PersonalizadaModel test = new PersonalizadaModel(i);
                ListaColores.Add(test);
            }
            ListaColores[27] = new PersonalizadaModel(27, "gray");
            ListaColores[28] = new PersonalizadaModel(28, "gray");
            ListaColores[35] = new PersonalizadaModel(35, "gray");
            ListaColores[36] = new PersonalizadaModel(36, "gray");
            TempData["Turno"] = "J1";
            TempData["Color"] = colores[0];
            return View(ListaColores);
        }
        public ActionResult Tiro(int io)
        {
            if (io != -1)
            {
                if (TempData["Turno"].Equals("J1"))
                {
                    PersonalizadaModel fichaNueva = new PersonalizadaModel(io, colores[color1]);
                    ListaColores[io] = fichaNueva;
                    TempData["Color"] = colores2[color2];
                    TempData["Turno"] = "J2";
                    J1();
                }
                else
                {
                    PersonalizadaModel fichaNueva = new PersonalizadaModel(io, colores2[color2]);
                    ListaColores[io] = fichaNueva;
                    TempData["Color"] = colores[color1];
                    TempData["Turno"] = "J1";
                    J2();
                }
            }
            return View("Personalizada", ListaColores);
        }
        public int J1()
        {
            if (color1 < colores.Count-1)
            {
                color1++;
            }
            else
            {
                color1 = 0;
            }
            return color1;
        }
        public int J2()
        {
            if (color2 < colores2.Count-1)
            {
                color2++;
            }
            else
            {
                color2 = 0;
            }
            return color2;
        }
        public void VerificarTiro(int io)
        {

        }
        public Boolean VerificarArriba(int io2)
        {
            int aux = io2 - 8;
            List<int> arriba = new List<int>();
            //Revisar Arriba
            if (aux < 0)
            {
                return false;
            }
            else
            {
                while (aux >= 0)
                {
                    if (aux < 0)
                    {
                        return false;
                    }
                    else
                    {
                        if (colores2.Contains(ListaColores[io2].Color))
                        {
                            if (ListaColores[aux].Color.Equals("") || ListaColores[aux].Color.Equals("gray"))
                            {
                                return false;
                            }
                            else
                            {
                                arriba.Add(aux);
                                aux = aux - 8;
                            }

                        }
                        else
                        {
                            if (arriba.Count() == 0)
                            {
                                return false;
                            }
                            else
                            {
                                for (int x = 0; x < arriba.Count(); x++)
                                {
                                    if (TempData["Color"].Equals("white"))
                                    {
                                        PersonalizadaModel fichaNueva = new PersonalizadaModel(arriba[x], "black");
                                        ListaColores[arriba[x]] = fichaNueva;
                                        TempData["Color"] = "white";
                                    }
                                    else if (TempData["Color"].Equals("black"))
                                    {
                                        PersonalizadaModel fichaNueva = new PersonalizadaModel(arriba[x], "white");
                                        ListaColores[arriba[x]] = fichaNueva;
                                        TempData["Color"] = "black";
                                    }
                                }

                            }
                            aux = -1;
                        }
                    }
                }
                return true;
            }
        }
    }
}

Repetido/Controllers/ExtremeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repetido.Models.Modelos;

namespace Repetido.Controllers
{
    public class ExtremeController : Controller
    {
        static List<PartidaIndividual> listaT = new List<PartidaIndividual>();
        static List<PartidaIndividual> listaC = new List<PartidaIndividual>();
        static List<int> posibles = new List<int>();
        static string J1 = "";
        static string C1 = "";
        static string J2 = "";
        static string C2 = "";
<<<<<<< HEAD
        static bool respuesta, fin = false;
=======
>>>>>>> e856601fc95f0bac20a0f92c0280f217e235814e
        static int TirosNegros = 0;
        static int TirosBlancos = 0;
        public ActionResult RetroInverso()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RetroInverso(string nombre, string color)
        {
            J1 = LoginController.user;
            TempData["J1"] = J1;
            if (nombre != null && color != null)
            {
                J2 = nombre;
                TempData["J2"] = J2;
                if (color == "Blanco")
                {
                    C2 = "white";
                    TempData["C2"] = C2;
                    TempData["C1"] = "black";
                }
                else
                {
                    C2 = "black";
                    TempData["C2"] = C2;
                    TempData["C1"] = "white";
                }
            }
            else
            {
                J2 = "Invitado";
                C2 = "white";
                TempData["C1"] = "black";
                TempData["J2"] = J2;
                TempData["C2"] = C2;
            }
            TempData["title"] = "Individual";
            for (int i = 0; i < 64; i++)
            {
                PartidaIndividual test = new PartidaIndividual(i);
                listaT.Add(test);
                listaC.Add(test);
            }
            listaT[27] = new PartidaIndividual(27, "black");
            listaT[36] = new PartidaIndividual(36, "black");
            listaT[28] = new PartidaIndividual(28, "white");
            listaT[35] = new PartidaIndividual(35, "white");
            listaT[20] = new PartidaIndividual(20, "gray");
            listaT[29] = new PartidaIndividual(29, "gray");
            listaT[34] = new PartidaIndividual(34, "gray");
            listaT[43] = new PartidaIndividual(43, "gray");
            posibles.Add(20);
            posibles.Add(29);
            posibles.Add(34);
            posibles.Add(43);
            TempData["Color"] = "black";
            TempData["TirosBlancos"] = 0;
            TempData["TirosNegros"] = 0;
            TempData["Fin"] = false;
            return View(listaT);
        }

        public ActionResult Tiro(int io)
        {
            if (io != -1)
            {
                if (TempData["Color"].Equals("black"))
                {
                    PartidaIndividual fichaNueva = new PartidaIndividual(io, "black");
                    listaT[io] = fichaNueva;
                    TempData["Color"] = "white";
                }
                else
                {
                    PartidaIndividual fichaNueva = new PartidaIndividual(io, "white");
                    listaT[io] = fichaNueva;
                    TempData["Color"] = "black";
                }
                change2(io);
                movimientosPosibles(io);

            }
            TempData["J1"] = J1;
            TempData["C1"] = C1;
            TempData["J2"] = J2;
            TempData["C2"] = C2;
            return View("RetroInverso", listaT);
        }

        public ActionResult TerminarPartida()
        {
            int punteo, movimientos;
            if (TempData["C1"].Equals("black"))
            {
                punteo = (int)TempData["PunteoNegras"];
                movimientos = TirosNegros;
            }
            else
            {
                punteo = (int)TempData["PunteoBlancas"];
                movimientos = TirosBlancos;
            }
            int userId = LoginController.idUser;
            using (BaseDatos2 db = new BaseDatos2())
            {
                var partida = new Partida();
                partida.Tipo = "RetroInverso";
                partida.Id_Jugador1 = userId;
                partida.Punteo = punteo;
                partida.Movimiento = movimientos;
                if (TempData["Ganador"].Equals(J1))
                {
                    partida.Ganador = "Ganada";
                }
                else if (TempData["Ganador"].Equals(J2))
                {
                    partida.Ganador = "Perdida";
                }
                else if (TempData["Ganador"].Equals("Empate"))
                {
                    partida.Ganador = "Empatada";
                }
                db.Partida.Add(partida);
                db.SaveChanges();
            }
            listaC.Clear();
            listaT.Clear();
            return RedirectToAction("Xtreme", "Apertura");
        }

        public Boolean VerificarArriba(int io2)
        {
            int aux = io2 - 8;
            List<int> arriba = new List<int>();
            //Revisar Arriba
            if (aux < 0)
            {
                return false;
            }
            else
            {
                while (aux >= 0)
                {
                    if (aux < 0)
                    {
                        return false;
                    }
                    else
                    {
                        if (listaT[io2].Color != listaT[aux].Color)
                        {
                            if (listaT[aux].Color.Equals("") || listaT[aux].Color.Equals("gray"))
                            {
                                return false;
                            }
                            else
                            {
                                arriba.Add(aux);
                                aux = aux - 8;
                            }

                        }
                        else
                        {
                            if (arriba.Count() == 0)
                            {
                                return false;
                            }
                            else
                            {
                                for (int x = 0; x < arriba.Count(); x++)
                                {
                                    if (TempData["Color"].Equals("white"))
                                    {
                                        PartidaIndividual fichaNueva = new PartidaIndividual(arriba[x], "black");
                                        listaT[arriba[x]] = fichaNueva;
                                        TempData["Color"] = "white";
                                    }
                                    else if (TempData["Color"].Equals("black"))
                                    {
                                        PartidaIndividual fichaNueva = new PartidaIndividual(arriba[x], "white");
                                        listaT[arriba[x]] = fichaNueva;
                                        TempData["Color"] = "black";
                                    }
                                }

                            }
                            aux = -1;
                        }
                    }
                }
                return true;
            }
        }

        public Boolean VerificarAbajo(int io2)
        {
            int aux2 = io2 + 8;
            List<int> abajo = new List<int>();
            //Revisar Abajo
            if (aux2 >= 64)
            {
                return false;
            }
            else
            {
                while (aux2 < 64)
                {
                    if (aux2 >= 64)
                    {
                        return false;
                    }
                    else
                    {
                        if (listaT[io2].Color != listaT[aux2].Color)
                        {
                            if (listaT[aux2].Color.Equals("") || listaT[aux2].Color.Equals("gray"))
                            {
                                return false;
                            }
                            else
                            {
                                abajo.Add(aux2);
                                aux2 = aux2 + 8;
                            }
                        }
                        else
                        {
                            if (abajo.Count() == 0)
                            {
                                return false;
                            }
                            else
                            {
                                for (int x = 0; x < abajo.Count(); x++)
                                {
                                    if (TempData["Color"].Equals("white"))
                                    {
                                        PartidaIndividual fichaNueva = new PartidaIndividual(abajo[x], "black");
                                        listaT[abajo[x]] = fichaNueva;
                                        TempData["Color"] = "white";
                                    }
                                    else if (TempData["Color"].Equals("black"))
                                    {
                                        PartidaIndividual fichaNueva = new PartidaIndividual(abajo[x], "white");
                                        listaT[abajo[x]] = fichaNueva;
                                        TempData["Color"] = "black";
                                    }
                                }
                            }
                            aux2 = 65;
                        }
                    }
                }
                return true;
            }

        }

Repetido/Views/Apertura/Xtreme.cshtml
@model List<Repetido.Models.Modelos.PersonalizadaModel>
@{
    ViewBag.Title = "Xtreme";
}
@section Image{
    '/Public/Image/E.jpg'
}
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/Content/MyStyles.css" />
    <link rel="stylesheet" href="~/Content/MyStyles2.css" />

</head>
<body>
    <header>
        <nav class="btn navbar float-right letra-negra align-content-lg-center">
            <a href="~/PantallaPrincipal/PantallaPrincipal" class="letra-negra"><div class="boton-atras black">X</div></a>
        </nav>
    </header>
    <header>
        <!-- Modal Apertuda Personalizada-->
        <div class="modal fade" id="Personalizada" tabindex="-1" role="dialog" aria-labelledby="Cargar" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content extreme tipo-letra text-white">
                    <div class="modal-header">
                        <div class="col">
                            <h4 class="modal-title align-content-center" id="exampleModalLongTitle">Colores @User.Identity.Name</h4>
                        </div>
                        <div class="col">
                            <h4 class="modal-title align-content-center" id="exampleModalLongTitle">Colores Invitado</h4>
                        </div>
                        <button class="close posible" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @using (Html.BeginForm("Personalizada", "Apertura"))
                    {
                        <form method="post">
                            <div class="modal-body">
                                <div class="row">
                                    @{string[] colores = { "Negro", "Blanco", "Rojo", "Cafe", "Anaranjado", "Magenta", "Verde", "Celeste", "Amarillo", "Azul" };

                                        <div class=" col">
                                            @for (int i = 0; i < 5; i++)
                                            {
                                                <div class="row align-content-left">
                                                    <div class="col">
                                                        <h5 class="tipo-letra">@colores[i]</h5>
                                                    </div>
                                                    <div class="col">
                                                        <input type="radio" name=@colores[i] value=@colores[i] />
                                                    </div>
                                                    <div class="col">
                                                        <h5 class="tipo-letra">@colores[i + 5]</h5>
                                                    </div>
                                                    <div class="col">
                                                        <input type="radio" name=@colores[i+5] value=@colores[i+5] />
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                    }
                                </div>
                            </div>
                            <div class="modal-footer">
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn red tipo-letra text-white " data-dismiss="modal">CERRRAR</button>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn black tipo-letra text-white">ACEPTAR</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
        <!-- Modal MultiPlayer RetroInverso -->
        <div class="modal fade" id="RetroInverso" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content extreme tipo-letra text-white">
                    <div class="modal-header">
                        <h5 class="modal-title align-content-center" id="exampleModalLongTitle">JUGADOR 2</h5>
                        <button class="close red redondear" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @using (Html.BeginForm("RetroInverso", "Extreme", FormMethod.Post))
                    {<form method="post">
                            <div class="modal-body">

                                <div class="form-group">
                                    <div class="row">
                                        <label> NOMBRE: </label>
                                        <div class="row">
                                            <div class="col">
                                                <input class="form-control" name="nombre" placeholder="Jugador 2" />
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <label> COLOR: </label>
                                        <div class="row">
                                            <div class="col">
                                                <label class="text-white tipo-letra">Blanco</label>
                                                <input type="radio" name="color" value="Blanco" />
                                            </div>
                                            <div class="col">
                                                <label class="text-white tipo-letra">Negro</label>
                                                <input type="radio" name="color" value="Negro" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn red tipo-letra text-white " data-dismiss="modal">CERRRAR</button>
                                    </div>

                                    <div class="col">
                                        <button type="submit" class="btn black tipo-letra text-white">ACEPTAR</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>

        <div class="row align-content-lg-center justify-content-center" style="height:60vh">
            <div class="col col-sm-4">
                <br />
                <br />
                <br />
                <br />
                <br />
                <div>
                    <button class="btn btn-block black redondear btn-outline-warning" data-toggle="modal" data-target="#RetroInverso"><h2 class="text-white align-content-center ">RETROINVERSO</h2></button>
                </div>
                <br />
                <br />
                <div>
                    <button class="btn btn-block black redondear btn-outline-warning" data-toggle="modal" data-target="#Personalizada"><h2 class="text-white align-content-center ">PERSONALIZADA</h2></button>
                </div>
                <br />
                <br />
            </div>
        </div>
    </header>
    <nav>
        <br />
        <footer>
            <nav class="navbar fixed-bottom nav navbar-collapse borde-amarillo extreme">
                <div class="col">
                    <h1 class=" tipo-letra text-white">OTHELLO</h1>
                </div>
                <div class="col">
                    <h1 class="align-content-left tipo-letra text-white">JUGAR</h1>
                </div>
                <div class="col">
                    <h1 class="align-content-left tipo-letra text-white">TORNEOS</h1>
                </div>
                <div class="col">
                    <h1 class="align-content-left tipo-letra text-white">HISTORIAL</h1>
                </div>
            </nav>
        </footer>
    </nav>
</body>