Repetido/Controllers/LocalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repetido.Models.Modelos;
using System.Xml.Linq;
using System.Xml;
using Repetido.Controllers;

namespace Repetido.Controllers
{
    [Authorize]
    public class LocalController : Controller
    {
        static List<PartidaIndividual> listaT = new List<PartidaIndividual>();
        static List<PartidaIndividual> listaC = new List<PartidaIndividual>();
        static List<int> posibles = new List<int>();
        static string J1 = "";
        static string C1 = "";
        static string J2 = "";
        static string C2 = "";
        static bool respuesta, fin = false;
        static int TirosNegros = 0;
        static int TirosBlancos = 0;
        
        public ActionResult Individual()
        {
            J1 = LoginController.user;
            J2 = "Zero Machine";
            TempData["J1"] = J1;
            C1 = "black";
            C2 = "white";
            TempData["C1"] = C1;
            TempData["C2"] = C2;
            TempData["title"] = "Individual";
            for (int i = 0; i < 64; i++)
            {
                PartidaIndividual test = new PartidaIndividual(i);
                listaT.Add(test);
                listaC.Add(test);
            }
            listaT[27] = new PartidaIndividual(27, "black");
            listaT[36] = new PartidaIndividual(36, "black");
            listaT[28] = new PartidaIndividual(28, "white");
            listaT[35] = new PartidaIndividual(35, "white");
            listaT[20] = new PartidaIndividual(20, "gray");
            listaT[29] = new PartidaIndividual(29, "gray");
            listaT[34] = new PartidaIndividual(34, "gray");
            listaT[43] = new PartidaIndividual(43, "gray");
            posibles.Add(20);
            posibles.Add(29);
            posibles.Add(34);
            posibles.Add(43);
            TempData["Color"] = "black";
            TempData["TirosBlancos"] = 0;
            TempData["TirosNegros"] = 0;
            return View(listaT);
        }

        public ActionResult Change(int io)
        {
            if (io != -1)
            {
                if (TempData["Color"].Equals("black"))
                {
                    PartidaIndividual fichaNueva = new PartidaIndividual(io, "black");
                    listaT[io] = fichaNueva;
                    TempData["Color"] = "white";
                }
                change2(io);
                movimientosPosibles(io);
                
                
            }
            while (TempData["Color"].Equals("white"))
            {
                int machine = -1;
                for(int x = 0; x<listaT.Count(); x++)
                {
                    if (listaT[x].Color.Equals("gray"))
                    {
                        machine = x;
                    }
                }
                if (machine != -1)
                {
                    PartidaIndividual fichaW = new PartidaIndividual(machine, "white");
                    listaT[machine] = fichaW;
                    TempData["Color"] = "black";
                    if (change2(machine) == true)
                    {
                        TempData["Color"] = "black";
                        movimientosPosibles(machine);
                    }
                    else
                    {
                        TempData["Color"] = "white";
                    }
                }
                else
                {
                    TempData["Color"] = "black";
                }

            }

            TempData["J1"] = J1;
            TempData["C1"] = C1;
            TempData["J2"] = J2;
            TempData["C2"] = C2;
            return View("Individual", listaT);
        }

        public ActionResult TerminarPartida()
        {
            int punteo = 0, movimientos = 0;
            if (TempData["C1"].Equals("black"))
            {
                punteo = (int)TempData["PunteoNegras"];
                movimientos = TirosNegros;
            }
            else
            {
                punteo = (int)TempData["PunteoBlancas"];
                movimientos = TirosBlancos;
            }
            int userId = LoginController.idUser;
            using (BaseDatos2 db = new BaseDatos2())
            {
                var partida = new Partida();
                partida.Tipo = "Solitario";
                partida.Id_Jugador1 = userId;
                partida.Punteo = punteo;
                partida.Movimiento = movimientos;
                if (TempData["Ganador"].Equals(J1))
                {
                    partida.Ganador = "Ganada";
                }
                else if (TempData["Ganador"].Equals(J2))
                {
                    partida.Ganador = "Perdida";
                }
                else if (TempData["Ganador"].Equals("Empate"))
                {
                    partida.Ganador = "Empatada";
                }
                db.Partida.Add(partida);
                db.SaveChanges();
            }
            listaT.Clear();
            return RedirectToAction("Jugar", "PantallaPrincipal");
        }

        public Boolean VerificarArriba(int io2)
        {
            int aux = io2 - 8;
            List<int> arriba = new List<int>();
            //Revisar Arriba
            if (aux < 0)
            {
                return false;
            }
            else
            {
                while (aux >= 0)
                {
                    if (aux < 0)
                    {
                        return false;
                    }
                    else
                    {
                        if (listaT[io2].Color != listaT[aux].Color)
                        {
                            if (listaT[aux].Color.Equals("") || listaT[aux].Color.Equals("gray"))
                            {
                                return false;
                            }
                            else
                            {
                                arriba.Add(aux);
                                aux = aux - 8;
                            }

                        }
                        else
                        {
                            if (arriba.Count() == 0)
                            {
                                return false;
                            }
                            else
                            {
                                for (int x = 0; x < arriba.Count(); x++)
                                {
                                    if (TempData["Color"].Equals("white"))
                                    {
                                        PartidaIndividual fichaNueva = new PartidaIndividual(arriba[x], "black");
                                        listaT[arriba[x]] = fichaNueva;
                                        TempData["Color"] = "white";
                                    }
                                    else if (TempData["Color"].Equals("black"))
                                    {
                                        PartidaIndividual fichaNueva = new PartidaIndividual(arriba[x], "white");
                                        listaT[arriba[x]] = fichaNueva;
                                        TempData["Color"] = "black";
                                    }
                                }

                            }
                            aux = -1;
                        }
                    }
                }
                return true;
            }
        }

        public Boolean VerificarAbajo(int io2)
        {
            int aux2 = io2 + 8;
            List<int> abajo = new List<int>();
            //Revisar Abajo
            if (aux2 >= 64)
            {
                return false;
            }
            else
            {
                while (aux2 < 64)
                {
                    if (aux2 >= 64)
                    {
                        return false;
                    }
                    else
                    {
                        if (listaT[io2].Color != listaT[aux2].Color)
                        {
                            if (listaT[aux2].Color.Equals("") || listaT[aux2].Color.Equals("gray"))
                            {
                                return false;
                            }
                            else
                            {
                                abajo.Add(aux2);
                                aux2 = aux2 + 8;
                            }
                        }
                        else
                        {
                            if (abajo.Count() == 0)
                            {
                                return false;
                            }
                            else
                            {
                                for (int x = 0; x < abajo.Count(); x++)
                                {
                                    if (TempData["Color"].Equals("white"))
                                    {
                                        PartidaIndividual fichaNueva = new PartidaIndividual(abajo[x], "black");
                                        listaT[abajo[x]] = fichaNueva;
                                        TempData["Color"] = "white";
                                    }
                                    else if (TempData["Color"].Equals("black"))
                                    {
                                        PartidaIndividual fichaNueva = new PartidaIndividual(abajo[x], "white");
                                        listaT[abajo[x]] = fichaNueva;
                                        TempData["Color"] = "black";
                                    }
                                }
                            }
                            aux2 = 65;
                        }
                    }
                }
                return true;

Repetido/Views/Local/Individual.cshtml
@{
    ViewBag.Title = "Individual";
}
@model List<Repetido.Models.Modelos.PartidaIndividual>
@{
    string filename = (string)TempData["file"];
}
@section Image{
    '/Public/Image/P.jpg'
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/Content/MyStyles2.css" />
    <link rel="stylesheet" href="~/Content/MyStyles.css" />
</head>
<body>
    <div>@filename</div>
    <div class="row">
        @{
            object negro = "", blanco = "";
            int negras = 0, blancas = 0;
            int tirosb = 0, tirosn = 0;
            string ganador = "";
            for (int x = 0; x < Model.Count(); x++)
            {
                if (Model[x].Color.Equals("black"))
                {
                    negras++;
                }
                else if (Model[x].Color.Equals("white"))
                {
                    blancas++;
                }
            }
            TempData["PunteoBlancas"] = blancas;
            TempData["PunteoNegras"] = negras;
            blanco = "Zero Machine";
            negro = TempData["J1"];
            if (TempData["TirosBlancos"] != null && TempData["TirosNegros"] != null)
            {
                tirosb = (int)TempData["TirosBlancos"];
                tirosn = (int)TempData["TirosNegros"];
            }

            if (blancas > negras)
            {
                ganador = (string)blanco;
                TempData["Ganador"] = ganador;

            }
            else if (negras > blancas)
            {
                ganador = (string)negro;
                TempData["Ganador"] = ganador;
            }
            else if (negras == blancas)
            {
                TempData["Ganador"] = "Empate";
            }
        }

        <!-- Terminara la partida y regresara al menu Jugar mostrando primero los resultados de la misma -->
        <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="false">
            <div class="modal-dialog">
                <div class="modal-content black">
                    <div class="modal-header">
                        <h2 class="text-white tipo-letra" id="staticBackdropLabel">RESULTADOS</h2>
                    </div>
                    @using (Html.BeginForm("TerminarPartida", "Local"))
                    {
                        <div class="modal-body">
                            <div class="row">
                                <div class="col">
                                    <h5 class="text-white tipo-letra">JUGADOR</h5>
                                </div>
                                <div class="col">
                                    <h5 class="text-white  tipo-letra">TIROS</h5>
                                </div>
                                <div class="col">
                                    <h5 class="text-white tipo-letra">PUNTEO</h5>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <h5 class="text-white tipo-letra">@negro</h5>
                                </div>
                                <div class="col">
                                    <h5 class="text-white  tipo-letra">@tirosn</h5>
                                </div>
                                <div class="col">
                                    <h5 class="text-white tipo-letra">@negras</h5>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <h5 class="text-white tipo-letra">@blanco</h5>
                                </div>
                                <div class="col">
                                    <h5 class="text-white  tipo-letra">@tirosb</h5>
                                </div>
                                <div class="col">
                                    <h5 class="text-white tipo-letra">@blancas</h5>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col"></div>
                                <div class="col"><h2 class="text-white tipo-letra">GANADOR</h2></div>
                                <div class="col"></div>
                            </div>
                            <div class="row">
                                <div class="col"></div>
                                <div class="col"><h3 class="text-white tipo-letra">@ganador</h3></div>
                                <div class="col"></div>
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn blue btn-outline-warning">CONTINUAR</button>
                        </div>
                    }
                </div>
            </div>
        </div>

        <div class="col">
            <div id="tablero">
                <!-- CREACION DEL TABLERO-->
                @using (Html.BeginForm("Change", "Local"))
                {
                    int numero = 0;
                    string[] letras = { " ", "A", "B", "C", "D", "E", "F", "G", "H", " " };
                    <div class="row align-top font-weight-bold">
                        @for (int i = 0; i < letras.Length; i++)
                        {
                            <div class="casilla border-0">@letras[i]</div>
                        }
                    </div>

                    for (int i = 0; i < 8; i++)
                    {
                        var id2 = i + 1;
                        <div class="fila font-weight-bold">
                            <div class="casilla">@id2</div>
                            @for (int j = 0; j < 8; j++)
                            {
                                if (Model[numero].Color.Equals("black"))
                                {
                                    <div class="casilla verdecitochido">
                                        <button class="btn fichas black">
                                        </button>
                                    </div>
                                }
                                else if (Model[numero].Color == "white")
                                {
                                    <div class="casilla verdecitochido">
                                        <button class="btn fichas white">
                                        </button>
                                    </div>

                                }
                                else if (Model[numero].Color == "gray")
                                {
                                    <div class="casilla verdecitochido">
                                        <button class="btn fichas posible" type="submit" value="@numero" name="io">
                                        </button>
                                    </div>
                                }
                                else
                                {
                                    <div class="casilla verdecitochido">
                                        <div class="btn verdecitochido fichas">
                                        </div>
                                    </div>
                                }
                                numero++;
                            }
                            <div class="casilla border-0">@id2</div>
                        </div>
                    }
                    <div class="row font-weight-bold">
                        @for (int i = 0; i < letras.Length; i++)
                        {
                            <div class="col casilla border-0">@letras[i]</div>
                        }
                    </div>
                }
            </div>
        </div>
        <div class="col">
            <!-- CREACION DEL TABLERO DE PUNTEOS, CARGAR Y DESCARGAR PARTIDA-->
            <div id="tablero2">
                <div class="row marron borde1">
                    @{ string[] punteo = { " ", " ", " ", "P", "U", "N", "T", "E", "O" };
                        <div class="fila font-weight-bold">
                            @for (int x = 0; x < punteo.Length; x++)
                            {
                                <div class="casilla border-0">@punteo[x]</div>
                            }
                        </div>
                    }
                </div>

                <div class="row">

                    <div class="col">
                        <div class="row" id="posicion">
                            <div class="col align-content-center">
                                <div class="fichas2 black">
                                </div>
                                <h3 class="text-white tipo-letra">@negro : @tirosn</h3>
                                <h2 class="text-white">@TempData["TirosNegros"]</h2>
                            </div>
                            <div class="col puntaje green2" id="contenedor">@negras</div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row" id="posicion">
                            <div class="col align-content-center">
                                <div class="fichas2 white">
                                </div>
                                <h3 class="text-white tipo-letra">@blanco : @tirosb</h3>
                                <h2 class="text-white">@TempData["TirosBlancos"]</h2>
                            </div>
                            <div class="col puntaje green2" id="contenedor">@blancas</div>
                        </div>
                    </div>
                </div>
                <div class="row marron border-0">
                    @{ string[] turno = { " ", " ", " ", "T", "U", "R", "N", "O" };
                        <div class="fila font-weight-bold">
                            @for (int x = 0; x < turno.Length; x++)
                            {
                                <div class="casilla border-0">@turno[x]</div>
                            }
                        </div>
                    }
                </div>
                <div class="row">
                    <div class="col">
                        <div class="row" id="posicion2">
                            <div class=" align-content-center">
                                @if (TempData["Color"].Equals("black"))
                                {
                                    <div class="fichas2 black"></div>
                                    TempData["Color"] = "black";
                                }
                                else if (TempData["Color"].Equals("white"))
                                {
                                    <div class="fichas2 white"></div>
                                    TempData["Color"] = "white";
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="posicionBotonoes">
                <div class="row">
                    <div class="col">
                        @using (Html.BeginForm("Load", "PantallaPrincipal"))
                        {
                            <button class="black text-white tipo-letra btn">Descargar Partida</button>
                        }
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <button type="button" class="black text-white tipo-letra btn" data-toggle="modal" data-target="#staticBackdrop">
                            Terminar Partida
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav>
        <br />
        <footer>
            <nav class="navbar fixed-bottom nav navbar-collapse borde-amarillo green2">
                <div class="col">
                    <h1 class=" tipo-letra text-white">OTHELLO</h1>
                </div>
                <div class="col">
                </div>
                <div class="col">
                </div>
                <div class="col">
                </div>
            </nav>
        </footer>
    </nav>
</body>
</html>